version: "3"
services:
  app:
    build:
      args:
        user: ticket
        uid: 1000
      context: ./.docker
      dockerfile: Dockerfile
    container_name: ${DOCKER_CONTAINER_BACKEND:-tlsoft_hr}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker:/data
    networks:
      - backend_network
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: ${DOCKER_CONTAINER_NGINX:-tlsoft_hr_nginx}
    restart: unless-stopped
    ports:
      - "${DOCKER_APP_PORT:-8008}:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - backend_network
    depends_on:
      - app
  db:
    image: "mariadb"
    restart: unless-stopped
    container_name: ${DOCKER_CONTAINER_MARIADB:-tlsoft_hr_mariadb}
    environment:
      MARIADB_ROOT_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tlsoft_hr
      MYSQL_USER: user
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    volumes:
      - "tlsoft-hr-mariadb:/var/lib/mysql"
    networks:
      - backend_network
  phpmyadmin:
    image: "phpmyadmin"
    container_name: ${DOCKER_CONTAINER_PHPMYADMIN:-tlsoft_hr_phpmyadmin}
    environment:
      - PMA_HOST=${DOCKER_CONTAINER_MARIADB:-tlsoft_hr_mariadb}
      - PMA_PORT=3306
    ports:
      - "${DOCKER_PHPMYADMIN_PORT:-8009}:80"
    networks:
      - backend_network
networks:
  backend_network:
    external:
      name: docker_default
    driver: bridge
volumes:
  tlsoft-hr-mariadb:
    driver: local
